### ISSUE TITLE
?? Null Coalesce Operator (since PHP 7)

### ISSUE THREAD

**Issue by johnish** [cronofy/cronofy-php-sample-app#7]
I'm running 5.5.35 and the isset ternary operator '??' is not available.

$_POST['availabilityInfo']['duration'] ?? "60"

**Comment by stephenbinns** [comment]
Hi Jon,  

Sorry for delay in getting back to you, we are only supporting php versions 7 or later with this sample app. I've updated the readme file to clarify this. 

Thanks,
Stephen
